//
//  BusinessCalenderModels.swift
//  iBeauty
//
//  Created by Nitesh Chauhan on 4/3/18.
//  Copyright (c) 2018 Kashish Verma. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum BusinessCalender
{
  // MARK: Use cases
  
    struct Request
    {
    }
    struct Response
    {
    }
    struct ViewModel
    {
    }
 
}
