//
//  BusinessCalenderRouter.swift
//  iBeauty
//
//  Created by Nitesh Chauhan on 4/3/18.
//  Copyright (c) 2018 Kashish Verma. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

 protocol BusinessCalenderRoutingLogic
{
 func routeToAppoinmentDetail(segue: UIStoryboardSegue?, orderDetailArray: BusinessToday.ViewModel.tableCellData)
}

protocol BusinessCalenderDataPassing
{
  var dataStore: BusinessCalenderDataStore? { get }
}

class BusinessCalenderRouter: NSObject, BusinessCalenderRoutingLogic, BusinessCalenderDataPassing
{
    
    
  weak var viewController: BusinessCalenderViewController?
  var dataStore: BusinessCalenderDataStore?
  
  // MARK: Routing
  
    func routeToAppoinmentDetail(segue: UIStoryboardSegue?, orderDetailArray: BusinessToday.ViewModel.tableCellData) {
        let destinationVC = viewController?.storyboard?.instantiateViewController(withIdentifier: ViewControllersIds.BusinessAppointmentDetailViewControllerID) as! BusinessAppointmentDetailViewController
        var destinationDS = destinationVC.router!.dataStore!
        passDataToSomewhere(source: dataStore!, destination: &destinationDS, orderDetailArray: orderDetailArray)
        navigateToSomewhere(source: viewController!, destination: destinationVC)
    }
  // MARK: Navigation
  
  func navigateToSomewhere(source: BusinessCalenderViewController, destination: BusinessAppointmentDetailViewController)
  {
    viewController?.navigationController?.pushViewController(destination, animated: true)
  }
  
  // MARK: Passing data
  
  func passDataToSomewhere(source: BusinessCalenderDataStore, destination: inout BusinessAppointmentDetailDataStore, orderDetailArray: BusinessToday.ViewModel.tableCellData)
  {
   destination.orderDetailArray = orderDetailArray
  }
}
