//
//  SelectBlockWorker.swift
//  iBeauty
//
//  Created by Apple on 12/10/18.
//  Copyright (c) 2018 Kashish Verma. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

class SelectBlockWorker
{
    func getBlockList(apiResponse:@escaping(responseHandler)) {
        let url = ApiEndPoints.userModule.getBlocks
        NetworkingWrapper.sharedInstance.connect(urlEndPoint: url, httpMethod: .get, headers: ApiHeaders.sharedInstance.headerWithLang()) { (response) in
            apiResponse(response)
        }
    }
}
