//
//  SelectBlockModels.swift
//  iBeauty
//
//  Created by Apple on 12/10/18.
//  Copyright (c) 2018 Kashish Verma. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum SelectBlock {
  // MARK: Use cases
    struct Request {
    }
    struct Response {
        let block: String?
        let blockId: String?
    }
    struct ViewModel {
        let list: [Response]
    }
}
