//
//  SelectBlockPresenter.swift
//  iBeauty
//
//  Created by Apple on 12/10/18.
//  Copyright (c) 2018 Kashish Verma. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol SelectBlockPresentationLogic
{
  func presentResponse(response: ApiResponse)
  func presentScreenName(screenNameText:String?)
}

class SelectBlockPresenter: SelectBlockPresentationLogic
{
  weak var viewController: SelectBlockDisplayLogic?
  
  // MARK: Do something
  
    func presentResponse(response: ApiResponse) {
        if response.error != nil {
            CustomAlertController.sharedInstance.showErrorAlert(error: response.error!.description)
        } else {
            let responseArr = response.result as? [Any]
            var list = [SelectBlock.Response]()
            for dic in responseArr! {
                let infoDic = dic as? [String: AnyObject]
                let item = SelectBlock.Response(
                    block: infoDic!["block"] as? String,
                    blockId: infoDic!["blockId"] as? String
                )
                list.append(item)
            }
            let viewModel = SelectBlock.ViewModel(list: list)
            viewController?.displayData(viewModel)
        }
    }
    
    func presentScreenName(screenNameText: String?) {
        viewController?.displayScreenName(ResponseMsg: screenNameText)
    }
}
